// TAP EGYPT Mock Database - Authentic Egyptian Real Estate Inventory

const TAP_EGYPT_DATA = {
  properties: [
    {
      id: "sodic-vye-116",
      slug: "sodic-vye-ground-apartment",
      title: "Sodic - VYE",
      developer: "SODIC",
      project: "VYE",
      propertyType: "Ground Floor",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 2,
      bathrooms: 2,
      area: 116,
      gardenArea: 40,
      downpayment: 5605000,
      totalPrice: 8428000,
      installments: 188000,
      remainingAmount: 2823000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png",
        "images/mountain_view.png"
      ],
      features: ["2 Bedrooms", "2 Bathrooms", "Garden", "Landscape"],
      notes: `Vye - sodic ✨\nGround apartment\n116 m + 40 m Garden\n2 Bedrooms\n2 Bathrooms\nReady to move\nFully finished\n\nRemaining 2,823,000\nTotal 8,428,000\nNext installment 9-2026 (188,245)\n\nRemaining installment club\n(77,694)\n\nNext installment club 9-2026 (38,847)\n\n+Buyer Commission 1.5%\n+transfer fees 50k`,
      financialSummary: {
        area: "116 m²",
        category: "For Resale",
        totalPrice: "8,428,000 EGP",
        finishing: "Fully Finished",
        downpayment: "5,605,000 EGP",
        installments: "188,000 EGP",
        gardenRoofLand: "40 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "TAP EGYPT Verified Resale Desk",
        phone: "+201001234567",
        whatsapp: "201001234567"
      }
    },
    {
      id: "newgiza-seashell-playa-haze",
      slug: "newgiza-seashell-playa-haze-chalet",
      title: "City Edge Developments",
      developer: "City Edge",
      project: "Alamein Towers",
      propertyType: "Haze Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 3,
      bathrooms: 3,
      area: 185,
      gardenArea: 0,
      downpayment: 16840000,
      totalPrice: 19000000,
      installments: 270000,
      remainingAmount: 2160000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "1st Floor",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/azha_north_coast.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Sea View", "Fully Furnished"],
      notes: `NEWGIZA - SEASHELL PLAYA ✨\nHaze Chalet - First Row Lagoon\n185 m² Prime location\n3 Bedrooms + Nanny Room\n3 Bathrooms\nReady to move immediately\nFully finished with ACs\n\nRemaining 2,160,000 EGP\nTotal 19,000,000 EGP\n\n+Buyer Commission 1.5%`,
      financialSummary: {
        area: "185 m²",
        category: "For Resale",
        totalPrice: "19,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "16,840,000 EGP",
        installments: "270,000 EGP",
        gardenRoofLand: "Roof Terrace",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "North Coast Resale Specialist",
        phone: "+201099887766",
        whatsapp: "201099887766"
      }
    },
    {
      id: "bliss-gate-torec-3b",
      slug: "torec-bliss-gate-apartment",
      title: "Torec Developments - Bliss Gate",
      developer: "Torec Developments",
      project: "Bliss Gate",
      propertyType: "Apartment",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 3,
      bathrooms: 2,
      area: 145,
      gardenArea: 0,
      downpayment: 4257327,
      totalPrice: 7887863,
      installments: 150000,
      remainingAmount: 3630536,
      finishing: "Semi Finished",
      deliveryDate: "2026",
      floor: "2nd Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/zed_west.png",
      gallery: [
        "images/zed_west.png",
        "images/sodic_vye.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Elevator", "Security"],
      notes: `Bliss Gate Sheikh Zayed\nApartment 145 m²\n3 Bedrooms, 2 Bathrooms\nSemi Finished\nDelivery Q4 2026\nDownpayment 4,257,327 EGP\nTotal 7,887,863 EGP`,
      financialSummary: {
        area: "145 m²",
        category: "For Resale",
        totalPrice: "7,887,863 EGP",
        finishing: "Semi Finished",
        downpayment: "4,257,327 EGP",
        installments: "150,000 EGP",
        gardenRoofLand: "Balcony",
        deliveryDate: "2026"
      },
      agent: {
        name: "Zayed Sales Desk",
        phone: "+201011223344",
        whatsapp: "201011223344"
      }
    },
    {
      id: "mountain-view-icity-penthouse",
      slug: "mountain-view-icity-penthouse",
      title: "Mountain View (DMG) - MOUNTAIN VIEW ICITY",
      developer: "Mountain View",
      project: "MOUNTAIN VIEW ICITY",
      propertyType: "Penthouse",
      category: "For Resale",
      isRent: false,
      location: "New Cairo",
      bedrooms: 3,
      bathrooms: 3,
      area: 215,
      gardenArea: 75,
      downpayment: 4550000,
      totalPrice: 5325000,
      installments: 96875,
      remainingAmount: 775000,
      finishing: "Core & Shell",
      deliveryDate: "Ready To Move",
      floor: "Roof Penthouse",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-07-15",
      image: "images/mountain_view.png",
      gallery: [
        "images/mountain_view.png",
        "images/azha_north_coast.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Private Roof", "Central Park View"],
      notes: `Mountain View iCity New Cairo\nPenthouse 215m + 75m Roof\n3 Bedrooms + 3 Bathrooms\nReady to move\nDownpayment: 4,550,000 EGP\nTotal Price: 5,325,000 EGP`,
      financialSummary: {
        area: "215 m²",
        category: "For Resale",
        totalPrice: "5,325,000 EGP",
        finishing: "Core & Shell",
        downpayment: "4,550,000 EGP",
        installments: "96,875 EGP",
        gardenRoofLand: "75 m² Roof",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "New Cairo Resale Team",
        phone: "+201055443322",
        whatsapp: "201055443322"
      }
    },
    {
      id: "azha-north-coast-chalet",
      slug: "madaar-azha-north-coast-chalet",
      title: "Madaar - Azha North Coast",
      developer: "Madaar",
      project: "Azha North Coast",
      propertyType: "Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 3,
      bathrooms: 2,
      area: 160,
      gardenArea: 0,
      downpayment: 10960726,
      totalPrice: 12500000,
      installments: 192400,
      remainingAmount: 1539274,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "Ground with Terrace",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-10",
      image: "images/azha_north_coast.png",
      gallery: [
        "images/azha_north_coast.png",
        "images/seashell_playa.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Crystal Lagoon View", "ACs Included"],
      notes: `Azha North Coast by Madaar\nChalet 160m² directly overlooking Crystal Lagoon\nFully finished with ACs & Kitchen Cabinets\n3 Bedrooms, 2 Bathrooms\nDelivery 2027\nDownpayment: 10,960,726 EGP\nTotal Price: 12,500,000 EGP`,
      financialSummary: {
        area: "160 m²",
        category: "For Resale",
        totalPrice: "12,500,000 EGP",
        finishing: "Fully Finished",
        downpayment: "10,960,726 EGP",
        installments: "192,400 EGP",
        gardenRoofLand: "Lagoon Front",
        deliveryDate: "2027"
      },
      agent: {
        name: "Coastal Properties Executive",
        phone: "+201088776655",
        whatsapp: "201088776655"
      }
    },
    {
      id: "inertia-joulz-ground",
      slug: "inertia-joulz-ground-floor",
      title: "INERTIA - Joulz",
      developer: "INERTIA",
      project: "Joulz",
      propertyType: "Ground Floor",
      category: "For Resale",
      isRent: false,
      location: "6 October",
      bedrooms: 3,
      bathrooms: 3,
      area: 190,
      gardenArea: 60,
      downpayment: 3800000,
      totalPrice: 8900000,
      installments: 127500,
      remainingAmount: 5100000,
      finishing: "Semi Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-05",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Private 60m Garden", "Underground Parking"],
      notes: `Inertia Joulz 6th of October\nGround Floor 190m² + 60m² Private Garden\n3 Bedrooms + 3 Bathrooms\nReady to move\nDownpayment: 3,800,000 EGP\nTotal Price: 8,900,000 EGP`,
      financialSummary: {
        area: "190 m²",
        category: "For Resale",
        totalPrice: "8,900,000 EGP",
        finishing: "Semi Finished",
        downpayment: "3,800,000 EGP",
        installments: "127,500 EGP",
        gardenRoofLand: "60 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "October Resale Desk",
        phone: "+201022334455",
        whatsapp: "201022334455"
      }
    },
    {
      id: "ora-zed-west-studio",
      slug: "ora-zed-west-studio",
      title: "Ora - ZED West",
      developer: "Ora Developers",
      project: "ZED West",
      propertyType: "Studio",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 1,
      bathrooms: 1,
      area: 68,
      gardenArea: 0,
      downpayment: 4340000,
      totalPrice: 4966456,
      installments: 78000,
      remainingAmount: 626456,
      finishing: "Fully Finished with ACs",
      deliveryDate: "Ready To Move",
      floor: "8th Floor Tower View",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/zed_west.png",
      gallery: [
        "images/zed_west.png",
        "images/mountain_view.png"
      ],
      features: ["1 Bedroom", "1 Bathroom", "Park View", "Tower Amenities"],
      notes: `Ora ZED West Tower Phase 2\nStudio 68m² overlooking Zed Park\nFully Finished with Air Conditioning & Kitchen Appliances\n1 Bedroom, 1 Bathroom\nReady to move\nDownpayment: 4,340,000 EGP\nTotal Price: 4,966,456 EGP`,
      financialSummary: {
        area: "68 m²",
        category: "For Resale",
        totalPrice: "4,966,456 EGP",
        finishing: "Fully Finished",
        downpayment: "4,340,000 EGP",
        installments: "78,000 EGP",
        gardenRoofLand: "Balcony View",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Ora Luxury Advisor",
        phone: "+201077665544",
        whatsapp: "201077665544"
      }
    },
    {
      id: "sodic-june-villa",
      slug: "sodic-june-twin-house",
      title: "SODIC - JUNE",
      developer: "SODIC",
      project: "JUNE North Coast",
      propertyType: "Twin House",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 4,
      bathrooms: 4,
      area: 260,
      gardenArea: 150,
      downpayment: 12500000,
      totalPrice: 24000000,
      installments: 320000,
      remainingAmount: 11500000,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "2 Levels + Roof",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/azha_north_coast.png"
      ],
      features: ["4 Bedrooms", "4 Bathrooms", "150m Garden", "Private Pool Option"],
      notes: `SODIC June North Coast\nTwin House Villa 260m² + 150m² Garden\n4 Master Bedrooms, 4 Bathrooms\nFully finished luxury specifications\nDownpayment: 12,500,000 EGP\nTotal Price: 24,000,000 EGP`,
      financialSummary: {
        area: "260 m²",
        category: "For Resale",
        totalPrice: "24,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "12,500,000 EGP",
        installments: "320,000 EGP",
        gardenRoofLand: "150 m² Garden",
        deliveryDate: "2027"
      },
      agent: {
        name: "SODIC Premium Desk",
        phone: "+201099112233",
        whatsapp: "201099112233"
      }
    },
    {
      id: "monte-galala-sokhna-rent",
      slug: "monte-galala-sokhna-chalet-rent",
      title: "Tatweer Misr - IL Monte Galala",
      developer: "Tatweer Misr",
      project: "IL Monte Galala",
      propertyType: "Chalet",
      category: "For Rent",
      isRent: true,
      location: "El Sokhna",
      bedrooms: 2,
      bathrooms: 2,
      area: 110,
      gardenArea: 0,
      downpayment: 0,
      totalPrice: 35000,
      rentPrice: 35000,
      installments: 0,
      remainingAmount: 0,
      finishing: "Fully Furnished",
      deliveryDate: "Ready To Move",
      floor: "Sea View Terrace",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-01",
      image: "images/mountain_view.png",
      gallery: [
        "images/mountain_view.png",
        "images/azha_north_coast.png"
      ],
      features: ["2 Bedrooms", "2 Bathrooms", "Panoramic Sea View", "Fully Furnished"],
      notes: `IL Monte Galala Sokhna Rental\nChalet 110m² Fully Furnished with Luxury Interiors\n2 Bedrooms, 2 Bathrooms\nMonthly Rent: 35,000 EGP / month\nAvailable immediately for long-term rental.`,
      financialSummary: {
        area: "110 m²",
        category: "For Rent",
        totalPrice: "35,000 EGP / Mo",
        finishing: "Fully Furnished",
        downpayment: "0 EGP",
        installments: "0 EGP",
        gardenRoofLand: "Sea View",
        deliveryDate: "Immediate"
      },
      agent: {
        name: "Sokhna Rental Specialist",
        phone: "+201044556677",
        whatsapp: "201044556677"
      }
    },
    {
      id: "madinaty-b12-rent",
      slug: "madinaty-b12-apartment-rent",
      title: "Talaat Moustafa - Madinaty B12",
      developer: "Talaat Moustafa Group",
      project: "Madinaty",
      propertyType: "Apartment",
      category: "For Rent",
      isRent: true,
      location: "Madinaty",
      bedrooms: 3,
      bathrooms: 2,
      area: 140,
      gardenArea: 0,
      downpayment: 0,
      totalPrice: 28000,
      rentPrice: 28000,
      installments: 0,
      remainingAmount: 0,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "4th Floor",
      license: "Basic",
      rating: 5,
      lastUpdated: "2026-08-08",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Wide Garden View", "Close to Craft Zone"],
      notes: `Madinaty B12 Group 123\nApartment 140m² Wide Garden View\n3 Bedrooms, 2 Bathrooms\nFully Finished\nMonthly Rent: 28,000 EGP / month`,
      financialSummary: {
        area: "140 m²",
        category: "For Rent",
        totalPrice: "28,000 EGP / Mo",
        finishing: "Fully Finished",
        downpayment: "0 EGP",
        installments: "0 EGP",
        gardenRoofLand: "Garden View",
        deliveryDate: "Immediate"
      },
      agent: {
        name: "Madinaty Rental Desk",
        phone: "+201033221100",
        whatsapp: "201033221100"
      }
    },
    {
      id: "hacienda-bay-villa",
      slug: "palm-hills-hacienda-bay-villa",
      title: "Palm Hills - Hacienda Bay",
      developer: "Palm Hills",
      project: "Hacienda Bay",
      propertyType: "Villa",
      category: "For Resale",
      isRent: false,
      location: "Hacienda",
      bedrooms: 5,
      bathrooms: 5,
      area: 380,
      gardenArea: 500,
      downpayment: 28000000,
      totalPrice: 45000000,
      installments: 420000,
      remainingAmount: 17000000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Standalone 2 Floors",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-09",
      image: "images/azha_north_coast.png",
      gallery: [
        "images/azha_north_coast.png",
        "images/seashell_playa.png"
      ],
      features: ["5 Bedrooms", "5 Bathrooms", "Private Heated Pool", "Golf View"],
      notes: `Hacienda Bay Standalone Villa\n380m² Built-up Area + 500m² Private Garden & Pool\n5 Master Bedrooms + Nanny Room\nGolf Course Frontline View\nDownpayment: 28,000,000 EGP\nTotal Price: 45,000,000 EGP`,
      financialSummary: {
        area: "380 m²",
        category: "For Resale",
        totalPrice: "45,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "28,000,000 EGP",
        installments: "420,000 EGP",
        gardenRoofLand: "500 m² Land",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Palm Hills Specialist",
        phone: "+201066778899",
        whatsapp: "201066778899"
      }
    },
    {
      id: "marina-1-lagoon-villa",
      slug: "marina-1-lagoon-villa",
      title: "Marina 1 - Lagoon Villa",
      developer: "Government / Emaar",
      project: "Marina North Coast",
      propertyType: "Villa",
      category: "For Resale",
      isRent: false,
      location: "Marina 1",
      bedrooms: 4,
      bathrooms: 3,
      area: 290,
      gardenArea: 300,
      downpayment: 18000000,
      totalPrice: 21500000,
      installments: 0,
      remainingAmount: 3500000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground + 1st",
      license: "Featured",
      rating: 4,
      lastUpdated: "2026-07-28",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/mountain_view.png"
      ],
      features: ["4 Bedrooms", "3 Bathrooms", "Lagoon Frontage", "Private Dock"],
      notes: `Marina 1 Waterfront Villa\n290m² + 300m² Garden directly on Lagoon\n4 Bedrooms, 3 Bathrooms\nFully renovated\nDownpayment: 18,000,000 EGP\nTotal Price: 21,500,000 EGP`,
      financialSummary: {
        area: "290 m²",
        category: "For Resale",
        totalPrice: "21,500,000 EGP",
        finishing: "Fully Finished",
        downpayment: "18,000,000 EGP",
        installments: "Cash / Direct",
        gardenRoofLand: "300 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Marina Resale Desk",
        phone: "+201022110099",
        whatsapp: "201022110099"
      }
    }
  ],

  locations: [
    { name: "Hacienda", count: 14, image: "images/azha_north_coast.png" },
    { name: "Marina 1", count: 9, image: "images/seashell_playa.png" },
    { name: "Marina 2", count: 12, image: "images/seashell_playa.png" },
    { name: "6 October", count: 38, image: "images/sodic_vye.png" },
    { name: "El Sheikh Zayed", count: 52, image: "images/zed_west.png" },
    { name: "El Sokhna", count: 24, image: "images/mountain_view.png" },
    { name: "Madinaty", count: 31, image: "images/sodic_vye.png" },
    { name: "New Cairo", count: 64, image: "images/mountain_view.png" },
    { name: "North Coast", count: 48, image: "images/azha_north_coast.png" }
  ],

  developers: [
    { name: "SODIC", count: 42, location: "Sheikh Zayed & New Cairo", logoImg: "images/developers_images/sodic.jpg" },
    { name: "Mountain View", count: 35, location: "New Cairo & North Coast", logoImg: "images/developers_images/mountainview.jpg" },
    { name: "Palm Hills", count: 39, location: "6 October & North Coast", logoImg: "images/developers_images/palmhills.png" },
    { name: "Emaar Misr", count: 32, location: "New Cairo & Marassi", logoImg: "images/developers_images/emaar.jpg" },
    { name: "INERTIA", count: 21, location: "North Coast & El Sokhna", logoImg: "images/developers_images/Al-Ahly-Sabbour.jpg" },
    { name: "Arco", count: 18, location: "North Coast & New Cairo", logoImg: "images/developers_images/intertia.png" },
    { name: "City Edge", count: 26, location: "New Alamein & Sheikh Zayed", logoImg: "images/developers_images/cityedge.jpg" },
    { name: "Karmell", count: 15, location: "El Sheikh Zayed", logoImg: "images/developers_images/almarasem.jpg" }
  ]
};

// Helper formatters
function formatCurrencyEGP(amount) {
  if (amount === undefined || amount === null) return "0 EGP";
  return amount.toLocaleString("en-US") + " EGP";
}
