// TAP EGYPT Mock Database - Authentic Egyptian Real Estate Inventory

const TAP_EGYPT_DATA = {
  properties: [
    {
      id: "sodic-vye-116",
      slug: "sodic-vye-ground-apartment",
      title: "Sodic - VYE",
      developer: "SODIC",
      project: "VYE",
      propertyType: "Ground Floor",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 2,
      bathrooms: 2,
      area: 116,
      gardenArea: 40,
      downpayment: 5605000,
      totalPrice: 8428000,
      installments: 188000,
      remainingAmount: 2823000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png",
        "images/mountain_view.png",
        "images/seashell_playa.png",
        "images/azha_north_coast.png",
        "images/luxury_hero_villa.png",
        "images/sodic_vye.png",
        "images/zed_west.png",
        "images/mountain_view.png",
        "images/seashell_playa.png",
        "images/azha_north_coast.png",
        "images/luxury_hero_villa.png",
        "images/sodic_vye.png",
        "images/zed_west.png",
        "images/mountain_view.png",
        "images/luxury_hero_villa.png"
      ],
      features: ["2 Bedrooms", "2 Bathrooms", "Garden", "Landscape"],
      notes: `Vye - sodic ✨\nGround apartment\n116 m + 40 m Garden\n2 Bedrooms\n2 Bathrooms\nReady to move\nFully finished\n\nRemaining 2,823,000\nTotal 8,428,000\nNext installment 9-2026 (188,245)\n\nRemaining installment club\n(77,694)\n\nNext installment club 9-2026 (38,847)\n\n+Buyer Commission 1.5%\n+transfer fees 50k`,
      financialSummary: {
        area: "116 m²",
        category: "For Resale",
        totalPrice: "8,428,000 EGP",
        finishing: "Fully Finished",
        downpayment: "5,605,000 EGP",
        installments: "188,000 EGP",
        gardenRoofLand: "40 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "TAP EGYPT Verified Resale Desk",
        phone: "+201001234567",
        whatsapp: "201001234567"
      }
    },
    {
      id: "newgiza-seashell-playa-haze",
      slug: "newgiza-seashell-playa-haze-chalet",
      title: "City Edge Developments",
      developer: "City Edge",
      project: "Alamein Towers",
      propertyType: "Haze Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 3,
      bathrooms: 3,
      area: 185,
      gardenArea: 0,
      downpayment: 16840000,
      totalPrice: 19000000,
      installments: 270000,
      remainingAmount: 2160000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "1st Floor",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/azha_north_coast.png",
        "images/luxury_hero_villa.png",
        "images/sodic_vye.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Sea View", "Fully Furnished"],
      notes: `NEWGIZA - SEASHELL PLAYA ✨\nHaze Chalet - First Row Lagoon\n185 m² Prime location\n3 Bedrooms + Nanny Room\n3 Bathrooms\nReady to move immediately\nFully finished with ACs\n\nRemaining 2,160,000 EGP\nTotal 19,000,000 EGP\n\n+Buyer Commission 1.5%`,
      financialSummary: {
        area: "185 m²",
        category: "For Resale",
        totalPrice: "19,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "16,840,000 EGP",
        installments: "270,000 EGP",
        gardenRoofLand: "Roof Terrace",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "North Coast Resale Specialist",
        phone: "+201099887766",
        whatsapp: "201099887766"
      }
    },
    {
      id: "bliss-gate-torec-3b",
      slug: "torec-bliss-gate-apartment",
      title: "Torec Developments - Bliss Gate",
      developer: "Torec Developments",
      project: "Bliss Gate",
      propertyType: "Apartment",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 3,
      bathrooms: 2,
      area: 145,
      gardenArea: 0,
      downpayment: 4257327,
      totalPrice: 7887863,
      installments: 150000,
      remainingAmount: 3630536,
      finishing: "Semi Finished",
      deliveryDate: "2026",
      floor: "2nd Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/zed_west.png",
      gallery: [
        "images/zed_west.png",
        "images/sodic_vye.png",
        "images/mountain_view.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Elevator", "Security"],
      notes: `Bliss Gate Sheikh Zayed\nApartment 145 m²\n3 Bedrooms, 2 Bathrooms\nSemi Finished\nDelivery Q4 2026\nDownpayment 4,257,327 EGP\nTotal 7,887,863 EGP`,
      financialSummary: {
        area: "145 m²",
        category: "For Resale",
        totalPrice: "7,887,863 EGP",
        finishing: "Semi Finished",
        downpayment: "4,257,327 EGP",
        installments: "150,000 EGP",
        gardenRoofLand: "Balcony",
        deliveryDate: "2026"
      },
      agent: {
        name: "Zayed Sales Desk",
        phone: "+201011223344",
        whatsapp: "201011223344"
      }
    },
    {
      id: "mountain-view-icity-penthouse",
      slug: "mountain-view-icity-penthouse",
      title: "Mountain View (DMG) - MOUNTAIN VIEW ICITY",
      developer: "Mountain View",
      project: "MOUNTAIN VIEW ICITY",
      propertyType: "Penthouse",
      category: "For Resale",
      isRent: false,
      location: "New Cairo",
      bedrooms: 3,
      bathrooms: 3,
      area: 215,
      gardenArea: 75,
      downpayment: 4550000,
      totalPrice: 5325000,
      installments: 96875,
      remainingAmount: 775000,
      finishing: "Core & Shell",
      deliveryDate: "Ready To Move",
      floor: "Roof Penthouse",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-07-15",
      image: "images/mountain_view.png",
      gallery: [
        "images/mountain_view.png",
        "images/azha_north_coast.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Private Roof", "Central Park View"],
      notes: `Mountain View iCity New Cairo\nPenthouse 215m + 75m Roof\n3 Bedrooms + 3 Bathrooms\nReady to move\nDownpayment: 4,550,000 EGP\nTotal Price: 5,325,000 EGP`,
      financialSummary: {
        area: "215 m²",
        category: "For Resale",
        totalPrice: "5,325,000 EGP",
        finishing: "Core & Shell",
        downpayment: "4,550,000 EGP",
        installments: "96,875 EGP",
        gardenRoofLand: "75 m² Roof",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "New Cairo Resale Team",
        phone: "+201055443322",
        whatsapp: "201055443322"
      }
    },
    {
      id: "azha-north-coast-chalet",
      slug: "madaar-azha-north-coast-chalet",
      title: "Madaar - Azha North Coast",
      developer: "Madaar",
      project: "Azha North Coast",
      propertyType: "Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 3,
      bathrooms: 2,
      area: 160,
      gardenArea: 0,
      downpayment: 10960726,
      totalPrice: 12500000,
      installments: 192400,
      remainingAmount: 1539274,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "Ground with Terrace",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-10",
      image: "images/azha_north_coast.png",
      gallery: [
        "images/azha_north_coast.png",
        "images/seashell_playa.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Crystal Lagoon View", "ACs Included"],
      notes: `Azha North Coast by Madaar\nChalet 160m² directly overlooking Crystal Lagoon\nFully finished with ACs & Kitchen Cabinets\n3 Bedrooms, 2 Bathrooms\nDelivery 2027\nDownpayment: 10,960,726 EGP\nTotal Price: 12,500,000 EGP`,
      financialSummary: {
        area: "160 m²",
        category: "For Resale",
        totalPrice: "12,500,000 EGP",
        finishing: "Fully Finished",
        downpayment: "10,960,726 EGP",
        installments: "192,400 EGP",
        gardenRoofLand: "Lagoon Front",
        deliveryDate: "2027"
      },
      agent: {
        name: "Coastal Properties Executive",
        phone: "+201088776655",
        whatsapp: "201088776655"
      }
    },
    {
      id: "inertia-joulz-ground",
      slug: "inertia-joulz-ground-floor",
      title: "INERTIA - Joulz",
      developer: "INERTIA",
      project: "Joulz",
      propertyType: "Ground Floor",
      category: "For Resale",
      isRent: false,
      location: "6 October",
      bedrooms: 3,
      bathrooms: 3,
      area: 190,
      gardenArea: 60,
      downpayment: 3800000,
      totalPrice: 8900000,
      installments: 127500,
      remainingAmount: 5100000,
      finishing: "Semi Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-05",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png"
      ],
      features: ["3 Bedrooms", "3 Bathrooms", "Private 60m Garden", "Underground Parking"],
      notes: `Inertia Joulz 6th of October\nGround Floor 190m² + 60m² Private Garden\n3 Bedrooms + 3 Bathrooms\nReady to move\nDownpayment: 3,800,000 EGP\nTotal Price: 8,900,000 EGP`,
      financialSummary: {
        area: "190 m²",
        category: "For Resale",
        totalPrice: "8,900,000 EGP",
        finishing: "Semi Finished",
        downpayment: "3,800,000 EGP",
        installments: "127,500 EGP",
        gardenRoofLand: "60 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "October Resale Desk",
        phone: "+201022334455",
        whatsapp: "201022334455"
      }
    },
    {
      id: "ora-zed-west-studio",
      slug: "ora-zed-west-studio",
      title: "Ora - ZED West",
      developer: "Ora Developers",
      project: "ZED West",
      propertyType: "Studio",
      category: "For Resale",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 1,
      bathrooms: 1,
      area: 68,
      gardenArea: 0,
      downpayment: 4340000,
      totalPrice: 4966456,
      installments: 78000,
      remainingAmount: 626456,
      finishing: "Fully Finished with ACs",
      deliveryDate: "Ready To Move",
      floor: "8th Floor Tower View",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/zed_west.png",
      gallery: [
        "images/zed_west.png",
        "images/mountain_view.png"
      ],
      features: ["1 Bedroom", "1 Bathroom", "Park View", "Tower Amenities"],
      notes: `Ora ZED West Tower Phase 2\nStudio 68m² overlooking Zed Park\nFully Finished with Air Conditioning & Kitchen Appliances\n1 Bedroom, 1 Bathroom\nReady to move\nDownpayment: 4,340,000 EGP\nTotal Price: 4,966,456 EGP`,
      financialSummary: {
        area: "68 m²",
        category: "For Resale",
        totalPrice: "4,966,456 EGP",
        finishing: "Fully Finished",
        downpayment: "4,340,000 EGP",
        installments: "78,000 EGP",
        gardenRoofLand: "Balcony View",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Ora Luxury Advisor",
        phone: "+201077665544",
        whatsapp: "201077665544"
      }
    },
    {
      id: "sodic-june-villa",
      slug: "sodic-june-twin-house",
      title: "SODIC - JUNE",
      developer: "SODIC",
      project: "JUNE North Coast",
      propertyType: "Twin House",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 4,
      bathrooms: 4,
      area: 260,
      gardenArea: 150,
      downpayment: 12500000,
      totalPrice: 24000000,
      installments: 320000,
      remainingAmount: 11500000,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "2 Levels + Roof",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-07-20",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/azha_north_coast.png"
      ],
      features: ["4 Bedrooms", "4 Bathrooms", "150m Garden", "Private Pool Option"],
      notes: `SODIC June North Coast\nTwin House Villa 260m² + 150m² Garden\n4 Master Bedrooms, 4 Bathrooms\nFully finished luxury specifications\nDownpayment: 12,500,000 EGP\nTotal Price: 24,000,000 EGP`,
      financialSummary: {
        area: "260 m²",
        category: "For Resale",
        totalPrice: "24,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "12,500,000 EGP",
        installments: "320,000 EGP",
        gardenRoofLand: "150 m² Garden",
        deliveryDate: "2027"
      },
      agent: {
        name: "SODIC Premium Desk",
        phone: "+201099112233",
        whatsapp: "201099112233"
      }
    },
    {
      id: "monte-galala-sokhna-rent",
      slug: "monte-galala-sokhna-chalet-rent",
      title: "Tatweer Misr - IL Monte Galala",
      developer: "Tatweer Misr",
      project: "IL Monte Galala",
      propertyType: "Chalet",
      category: "For Rent",
      isRent: true,
      location: "El Sokhna",
      bedrooms: 2,
      bathrooms: 2,
      area: 110,
      gardenArea: 0,
      downpayment: 0,
      totalPrice: 35000,
      rentPrice: 35000,
      installments: 0,
      remainingAmount: 0,
      finishing: "Fully Furnished",
      deliveryDate: "Ready To Move",
      floor: "Sea View Terrace",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-01",
      image: "images/mountain_view.png",
      gallery: [
        "images/mountain_view.png",
        "images/azha_north_coast.png"
      ],
      features: ["2 Bedrooms", "2 Bathrooms", "Panoramic Sea View", "Fully Furnished"],
      notes: `IL Monte Galala Sokhna Rental\nChalet 110m² Fully Furnished with Luxury Interiors\n2 Bedrooms, 2 Bathrooms\nMonthly Rent: 35,000 EGP / month\nAvailable immediately for long-term rental.`,
      financialSummary: {
        area: "110 m²",
        category: "For Rent",
        totalPrice: "35,000 EGP / Mo",
        finishing: "Fully Furnished",
        downpayment: "0 EGP",
        installments: "0 EGP",
        gardenRoofLand: "Sea View",
        deliveryDate: "Immediate"
      },
      agent: {
        name: "Sokhna Rental Specialist",
        phone: "+201044556677",
        whatsapp: "201044556677"
      }
    },
    {
      id: "madinaty-b12-rent",
      slug: "madinaty-b12-apartment-rent",
      title: "Talaat Moustafa - Madinaty B12",
      developer: "Talaat Moustafa Group",
      project: "Madinaty",
      propertyType: "Apartment",
      category: "For Rent",
      isRent: true,
      location: "Madinaty",
      bedrooms: 3,
      bathrooms: 2,
      area: 140,
      gardenArea: 0,
      downpayment: 0,
      totalPrice: 28000,
      rentPrice: 28000,
      installments: 0,
      remainingAmount: 0,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "4th Floor",
      license: "Basic",
      rating: 5,
      lastUpdated: "2026-08-08",
      image: "images/sodic_vye.png",
      gallery: [
        "images/sodic_vye.png",
        "images/zed_west.png"
      ],
      features: ["3 Bedrooms", "2 Bathrooms", "Wide Garden View", "Close to Craft Zone"],
      notes: `Madinaty B12 Group 123\nApartment 140m² Wide Garden View\n3 Bedrooms, 2 Bathrooms\nFully Finished\nMonthly Rent: 28,000 EGP / month`,
      financialSummary: {
        area: "140 m²",
        category: "For Rent",
        totalPrice: "28,000 EGP / Mo",
        finishing: "Fully Finished",
        downpayment: "0 EGP",
        installments: "0 EGP",
        gardenRoofLand: "Garden View",
        deliveryDate: "Immediate"
      },
      agent: {
        name: "Madinaty Rental Desk",
        phone: "+201033221100",
        whatsapp: "201033221100"
      }
    },
    {
      id: "hacienda-bay-villa",
      slug: "palm-hills-hacienda-bay-villa",
      title: "Palm Hills - Hacienda Bay",
      developer: "Palm Hills",
      project: "Hacienda Bay",
      propertyType: "Villa",
      category: "For Resale",
      isRent: false,
      location: "Hacienda",
      bedrooms: 5,
      bathrooms: 5,
      area: 380,
      gardenArea: 500,
      downpayment: 28000000,
      totalPrice: 45000000,
      installments: 420000,
      remainingAmount: 17000000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Standalone 2 Floors",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-09",
      image: "images/azha_north_coast.png",
      gallery: [
        "images/azha_north_coast.png",
        "images/seashell_playa.png"
      ],
      features: ["5 Bedrooms", "5 Bathrooms", "Private Heated Pool", "Golf View"],
      notes: `Hacienda Bay Standalone Villa\n380m² Built-up Area + 500m² Private Garden & Pool\n5 Master Bedrooms + Nanny Room\nGolf Course Frontline View\nDownpayment: 28,000,000 EGP\nTotal Price: 45,000,000 EGP`,
      financialSummary: {
        area: "380 m²",
        category: "For Resale",
        totalPrice: "45,000,000 EGP",
        finishing: "Fully Finished",
        downpayment: "28,000,000 EGP",
        installments: "420,000 EGP",
        gardenRoofLand: "500 m² Land",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Palm Hills Specialist",
        phone: "+201066778899",
        whatsapp: "201066778899"
      }
    },
    {
      id: "marina-1-lagoon-villa",
      slug: "marina-1-lagoon-villa",
      title: "Marina 1 - Lagoon Villa",
      developer: "Government / Emaar",
      project: "Marina North Coast",
      propertyType: "Villa",
      category: "For Resale",
      isRent: false,
      location: "Marina 1",
      bedrooms: 4,
      bathrooms: 3,
      area: 290,
      gardenArea: 300,
      downpayment: 18000000,
      totalPrice: 21500000,
      installments: 0,
      remainingAmount: 3500000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground + 1st",
      license: "Featured",
      rating: 4,
      lastUpdated: "2026-07-28",
      image: "images/seashell_playa.png",
      gallery: [
        "images/seashell_playa.png",
        "images/mountain_view.png"
      ],
      features: ["4 Bedrooms", "3 Bathrooms", "Lagoon Frontage", "Private Dock"],
      notes: `Marina 1 Waterfront Villa\n290m² + 300m² Garden directly on Lagoon\n4 Bedrooms, 3 Bathrooms\nFully renovated\nDownpayment: 18,000,000 EGP\nTotal Price: 21,500,000 EGP`,
      financialSummary: {
        area: "290 m²",
        category: "For Resale",
        totalPrice: "21,500,000 EGP",
        finishing: "Fully Finished",
        downpayment: "18,000,000 EGP",
        installments: "Cash / Direct",
        gardenRoofLand: "300 m² Garden",
        deliveryDate: "Ready To Move"
      },
      agent: {
        name: "Marina Resale Desk",
        phone: "+201022110099",
        whatsapp: "201022110099"
      }
    },
    {
      id: "emaar-marassi-white-villas",
      slug: "emaar-marassi-white-villas",
      title: "Emaar Misr - Marassi",
      developer: "Emaar Misr",
      project: "Marassi",
      propertyType: "Standalone Villa",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 4,
      bathrooms: 4,
      area: 320,
      gardenArea: 250,
      downpayment: 22500000,
      totalPrice: 36000000,
      installments: 450000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground + 1st",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-01",
      image: "images/luxury_hero_villa.png",
      gallery: ["images/luxury_hero_villa.png", "images/azha_north_coast.png"],
      features: ["4 Bedrooms", "4 Bathrooms", "Golf Frontage", "Private Pool"],
      notes: `Marassi Emaar Misr Villa\n320m² BUA + 250m² Private Garden & Heated Pool\n4 Master Bedrooms, 4 Bathrooms\nReady To Move Immediately\nDownpayment: 22,500,000 EGP\nTotal Price: 36,000,000 EGP`,
      financialSummary: { area: "320 m²", category: "For Resale", totalPrice: "36,000,000 EGP", finishing: "Fully Finished", downpayment: "22,500,000 EGP", installments: "450,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "Emaar Premier Desk", phone: "+201011223344", whatsapp: "201011223344" }
    },
    {
      id: "palm-hills-badya-penthouse",
      slug: "palm-hills-badya-penthouse",
      title: "Palm Hills - Badya",
      developer: "Palm Hills",
      project: "Badya",
      propertyType: "Penthouse",
      category: "Primary / Developer",
      isRent: false,
      location: "6 October",
      bedrooms: 3,
      bathrooms: 3,
      area: 210,
      downpayment: 3200000,
      totalPrice: 7500000,
      installments: 120000,
      finishing: "Semi Finished",
      deliveryDate: "2026",
      floor: "Penthouse",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-05",
      image: "images/sodic_vye.png",
      gallery: ["images/sodic_vye.png", "images/mountain_view.png"],
      features: ["3 Bedrooms", "3 Bathrooms", "Terrace", "Smart Home System"],
      notes: `Badya Palm Hills Penthouse\n210m² BUA with 45m² Open Roof Terrace\n3 Bedrooms, 3 Bathrooms\nDelivery Q3 2026\nDownpayment: 3,200,000 EGP\nTotal Price: 7,500,000 EGP`,
      financialSummary: { area: "210 m²", category: "Primary", totalPrice: "7,500,000 EGP", finishing: "Semi Finished", downpayment: "3,200,000 EGP", installments: "120,000 EGP", deliveryDate: "2026" },
      agent: { name: "Palm Hills Sales Team", phone: "+201099887766", whatsapp: "201099887766" }
    },
    {
      id: "tatweer-fouka-bay-chalet",
      slug: "tatweer-fouka-bay-chalet",
      title: "Tatweer Misr - Fouka Bay",
      developer: "Tatweer Misr",
      project: "Fouka Bay",
      propertyType: "Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 2,
      bathrooms: 2,
      area: 125,
      downpayment: 5100000,
      totalPrice: 9800000,
      installments: 180000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "1st Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-03",
      image: "images/azha_north_coast.png",
      gallery: ["images/azha_north_coast.png", "images/seashell_playa.png"],
      features: ["2 Bedrooms", "2 Bathrooms", "Crystal Lagoon View", "Fully Furnished"],
      notes: `Fouka Bay Chalet\n125m² Lagoon View\n2 Bedrooms, 2 Bathrooms\nReady To Move\nDownpayment: 5,100,000 EGP\nTotal Price: 9,800,000 EGP`,
      financialSummary: { area: "125 m²", category: "For Resale", totalPrice: "9,800,000 EGP", finishing: "Fully Finished", downpayment: "5,100,000 EGP", installments: "180,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "Tatweer Direct Desk", phone: "+201033445566", whatsapp: "201033445566" }
    },
    {
      id: "hassan-allam-swanlake-residences",
      slug: "hassan-allam-swanlake-residences",
      title: "Hassan Allam - Swanlake",
      developer: "Hassan Allam",
      project: "Swanlake Residences",
      propertyType: "Apartment",
      category: "Primary / Developer",
      isRent: false,
      location: "New Cairo",
      bedrooms: 3,
      bathrooms: 3,
      area: 175,
      downpayment: 6800000,
      totalPrice: 14200000,
      installments: 210000,
      finishing: "Fully Finished",
      deliveryDate: "2026",
      floor: "2nd Floor",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-08",
      image: "images/mountain_view.png",
      gallery: ["images/mountain_view.png", "images/zed_west.png"],
      features: ["3 Bedrooms", "3 Bathrooms", "Park View", "ACs Included"],
      notes: `Swanlake Residences Apartment\n175m² Prime Park View\n3 Bedrooms, 3 Bathrooms\nDelivery Q4 2026\nDownpayment: 6,800,000 EGP\nTotal Price: 14,200,000 EGP`,
      financialSummary: { area: "175 m²", category: "Primary", totalPrice: "14,200,000 EGP", finishing: "Fully Finished", downpayment: "6,800,000 EGP", installments: "210,000 EGP", deliveryDate: "2026" },
      agent: { name: "Hassan Allam Sales", phone: "+201066778899", whatsapp: "201066778899" }
    },
    {
      id: "orascom-o-west-townhouse",
      slug: "orascom-o-west-townhouse",
      title: "Orascom - O West",
      developer: "Orascom Development",
      project: "O West",
      propertyType: "Townhouse",
      category: "Primary / Developer",
      isRent: false,
      location: "6 October",
      bedrooms: 3,
      bathrooms: 3,
      area: 230,
      gardenArea: 80,
      downpayment: 4900000,
      totalPrice: 16500000,
      installments: 240000,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "Ground + 1st",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-10",
      image: "images/zed_west.png",
      gallery: ["images/zed_west.png", "images/sodic_vye.png"],
      features: ["3 Bedrooms", "3 Bathrooms", "80m Garden", "Clubhouse Access"],
      notes: `O West Townhouse Villa\n230m² BUA + 80m² Private Garden\n3 Bedrooms, 3 Bathrooms\nDelivery 2027\nDownpayment: 4,900,000 EGP\nTotal Price: 16,500,000 EGP`,
      financialSummary: { area: "230 m²", category: "Primary", totalPrice: "16,500,000 EGP", finishing: "Fully Finished", downpayment: "4,900,000 EGP", installments: "240,000 EGP", deliveryDate: "2027" },
      agent: { name: "Orascom Direct Desk", phone: "+201055443322", whatsapp: "201055443322" }
    },
    {
      id: "hydepark-new-cairo-apartment",
      slug: "hydepark-new-cairo-apartment",
      title: "Hyde Park - New Cairo",
      developer: "Hyde Park",
      project: "Hyde Park",
      propertyType: "Apartment",
      category: "For Resale",
      isRent: false,
      location: "New Cairo",
      bedrooms: 2,
      bathrooms: 2,
      area: 135,
      downpayment: 3900000,
      totalPrice: 8400000,
      installments: 140000,
      finishing: "Semi Finished",
      deliveryDate: "Ready To Move",
      floor: "3rd Floor",
      license: "Basic",
      rating: 4,
      lastUpdated: "2026-08-02",
      image: "images/mountain_view.png",
      gallery: ["images/mountain_view.png", "images/sodic_vye.png"],
      features: ["2 Bedrooms", "2 Bathrooms", "Central Park View", "Elevator"],
      notes: `Hyde Park New Cairo Apartment\n135m² Overlooking Central Park\n2 Bedrooms, 2 Bathrooms\nReady To Move\nDownpayment: 3,900,000 EGP\nTotal Price: 8,400,000 EGP`,
      financialSummary: { area: "135 m²", category: "For Resale", totalPrice: "8,400,000 EGP", finishing: "Semi Finished", downpayment: "3,900,000 EGP", installments: "140,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "Hyde Park Resale", phone: "+201088776655", whatsapp: "201088776655" }
    },
    {
      id: "mountain-view-ras-el-hekma-chalet",
      slug: "mountain-view-ras-el-hekma-chalet",
      title: "Mountain View - Ras El Hekma",
      developer: "Mountain View",
      project: "Ras El Hekma",
      propertyType: "Chalet",
      category: "For Resale",
      isRent: false,
      location: "North Coast",
      bedrooms: 3,
      bathrooms: 2,
      area: 140,
      downpayment: 6500000,
      totalPrice: 11200000,
      installments: 195000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground Floor",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-07",
      image: "images/seashell_playa.png",
      gallery: ["images/seashell_playa.png", "images/azha_north_coast.png"],
      features: ["3 Bedrooms", "2 Bathrooms", "Greek Style Architecture", "Lagoon Front"],
      notes: `Mountain View Ras El Hekma Chalet\n140m² Greek Villa Style\n3 Bedrooms, 2 Bathrooms\nReady To Move Immediately\nDownpayment: 6,500,000 EGP\nTotal Price: 11,200,000 EGP`,
      financialSummary: { area: "140 m²", category: "For Resale", totalPrice: "11,200,000 EGP", finishing: "Fully Finished", downpayment: "6,500,000 EGP", installments: "195,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "MV Coast Desk", phone: "+201044332211", whatsapp: "201044332211" }
    },
    {
      id: "sodic-villette-sky-condos",
      slug: "sodic-villette-sky-condos",
      title: "SODIC - Villette Sky Condos",
      developer: "SODIC",
      project: "Villette",
      propertyType: "Apartment",
      category: "For Resale",
      isRent: false,
      location: "New Cairo",
      bedrooms: 3,
      bathrooms: 3,
      area: 190,
      downpayment: 7400000,
      totalPrice: 15800000,
      installments: 260000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "4th Floor",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-09",
      image: "images/sodic_vye.png",
      gallery: ["images/sodic_vye.png", "images/mountain_view.png"],
      features: ["3 Bedrooms", "3 Bathrooms", "Terrace", "Underground Parking"],
      notes: `SODIC Villette Sky Condos\n190m² Open Skyline View\n3 Bedrooms, 3 Bathrooms\nReady To Move\nDownpayment: 7,400,000 EGP\nTotal Price: 15,800,000 EGP`,
      financialSummary: { area: "190 m²", category: "For Resale", totalPrice: "15,800,000 EGP", finishing: "Fully Finished", downpayment: "7,400,000 EGP", installments: "260,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "SODIC Sky Desk", phone: "+201077665544", whatsapp: "201077665544" }
    },
    {
      id: "city-edge-maspero-towers",
      slug: "city-edge-maspero-towers",
      title: "City Edge - Maspero Towers",
      developer: "City Edge",
      project: "Maspero Towers",
      propertyType: "Apartment",
      category: "Primary / Developer",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 2,
      bathrooms: 2,
      area: 115,
      downpayment: 5800000,
      totalPrice: 10500000,
      installments: 175000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "12th Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-11",
      image: "images/zed_west.png",
      gallery: ["images/zed_west.png", "images/sodic_vye.png"],
      features: ["2 Bedrooms", "2 Bathrooms", "Nile River View", "Luxury Finishes"],
      notes: `City Edge Maspero Towers Apartment\n115m² Panoramic View\n2 Bedrooms, 2 Bathrooms\nReady To Move\nDownpayment: 5,800,000 EGP\nTotal Price: 10,500,000 EGP`,
      financialSummary: { area: "115 m²", category: "Primary", totalPrice: "10,500,000 EGP", finishing: "Fully Finished", downpayment: "5,800,000 EGP", installments: "175,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "City Edge Central", phone: "+201011998877", whatsapp: "201011998877" }
    },
    {
      id: "azha-sokhna-waterfront-chalet",
      slug: "azha-sokhna-waterfront-chalet",
      title: "Madaar - Azha Ain Sokhna",
      developer: "INERTIA",
      project: "Azha Sokhna",
      propertyType: "Chalet",
      category: "For Resale",
      isRent: false,
      location: "El Sokhna",
      bedrooms: 2,
      bathrooms: 2,
      area: 105,
      downpayment: 4100000,
      totalPrice: 8100000,
      installments: 135000,
      finishing: "Fully Finished",
      deliveryDate: "Ready To Move",
      floor: "Ground Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-12",
      image: "images/azha_north_coast.png",
      gallery: ["images/azha_north_coast.png", "images/seashell_playa.png"],
      features: ["2 Bedrooms", "2 Bathrooms", "Crystal Lagoon Direct Access", "ACs & Kitchen"],
      notes: `Azha Ain Sokhna Chalet\n105m² Direct Lagoon Access\n2 Bedrooms, 2 Bathrooms\nReady To Move\nDownpayment: 4,100,000 EGP\nTotal Price: 8,100,000 EGP`,
      financialSummary: { area: "105 m²", category: "For Resale", totalPrice: "8,100,000 EGP", finishing: "Fully Finished", downpayment: "4,100,000 EGP", installments: "135,000 EGP", deliveryDate: "Ready To Move" },
      agent: { name: "Azha Sokhna Desk", phone: "+201022334455", whatsapp: "201022334455" }
    },
    {
      id: "sodic-karmell-zayed-villa",
      slug: "sodic-karmell-zayed-villa",
      title: "SODIC - Karmell Sheikh Zayed",
      developer: "SODIC",
      project: "Karmell",
      propertyType: "Standalone Villa",
      category: "Primary / Developer",
      isRent: false,
      location: "El Sheikh Zayed",
      bedrooms: 4,
      bathrooms: 4,
      area: 270,
      gardenArea: 180,
      downpayment: 14500000,
      totalPrice: 21000000,
      installments: 320000,
      finishing: "Fully Finished",
      deliveryDate: "2026",
      floor: "Ground + 1st",
      license: "Premium",
      rating: 5,
      lastUpdated: "2026-08-13",
      image: "images/sodic_vye.png",
      gallery: ["images/sodic_vye.png", "images/luxury_hero_villa.png"],
      features: ["4 Bedrooms", "4 Bathrooms", "180m Garden", "Californian Architecture"],
      notes: `SODIC Karmell Sheikh Zayed Villa\n270m² BUA + 180m² Private Garden\n4 Master Bedrooms, 4 Bathrooms\nDelivery Q4 2026\nDownpayment: 14,500,000 EGP\nTotal Price: 21,000,000 EGP`,
      financialSummary: { area: "270 m²", category: "Primary", totalPrice: "21,000,000 EGP", finishing: "Fully Finished", downpayment: "14,500,000 EGP", installments: "320,000 EGP", deliveryDate: "2026" },
      agent: { name: "SODIC Zayed Sales", phone: "+201099112233", whatsapp: "201099112233" }
    },
    {
      id: "ora-zed-east-apartment",
      slug: "ora-zed-east-apartment",
      title: "Ora Developers - ZED East",
      developer: "Ora Developers",
      project: "ZED East",
      propertyType: "Apartment",
      category: "Primary / Developer",
      isRent: false,
      location: "New Cairo",
      bedrooms: 3,
      bathrooms: 3,
      area: 165,
      downpayment: 5200000,
      totalPrice: 11800000,
      installments: 190000,
      finishing: "Fully Finished",
      deliveryDate: "2027",
      floor: "3rd Floor",
      license: "Featured",
      rating: 5,
      lastUpdated: "2026-08-14",
      image: "images/zed_west.png",
      gallery: ["images/zed_west.png", "images/mountain_view.png"],
      features: ["3 Bedrooms", "3 Bathrooms", "Club Park View", "ACs Included"],
      notes: `Ora ZED East New Cairo Apartment\n165m² Prime Club Park View\n3 Bedrooms, 3 Bathrooms\nDelivery 2027\nDownpayment: 5,200,000 EGP\nTotal Price: 11,800,000 EGP`,
      financialSummary: { area: "165 m²", category: "Primary", totalPrice: "11,800,000 EGP", finishing: "Fully Finished", downpayment: "5,200,000 EGP", installments: "190,000 EGP", deliveryDate: "2027" },
      agent: { name: "Ora Direct Sales", phone: "+201088223344", whatsapp: "201088223344" }
    }
  ],

  locations: [
    { name: "Hacienda", count: 14, image: "images/azha_north_coast.png" },
    { name: "Marina 1", count: 9, image: "images/seashell_playa.png" },
    { name: "Marina 2", count: 12, image: "images/seashell_playa.png" },
    { name: "6 October", count: 38, image: "images/sodic_vye.png" },
    { name: "El Sheikh Zayed", count: 52, image: "images/zed_west.png" },
    { name: "El Sokhna", count: 24, image: "images/mountain_view.png" },
    { name: "Madinaty", count: 31, image: "images/sodic_vye.png" },
    { name: "New Cairo", count: 64, image: "images/mountain_view.png" },
    { name: "North Coast", count: 48, image: "images/azha_north_coast.png" }
  ],

  developers: [
    { name: "SODIC", count: 42, location: "Sheikh Zayed & New Cairo", logoImg: "images/developers_images/sodic.jpg" },
    { name: "Mountain View", count: 35, location: "New Cairo & North Coast", logoImg: "images/developers_images/mountainview.jpg" },
    { name: "Palm Hills", count: 39, location: "6 October & North Coast", logoImg: "images/developers_images/palmhills.png" },
    { name: "Emaar Misr", count: 32, location: "New Cairo & Marassi", logoImg: "images/developers_images/emaar.jpg" },
    { name: "INERTIA", count: 21, location: "North Coast & El Sokhna", logoImg: "images/developers_images/Al-Ahly-Sabbour.jpg" },
    { name: "Arco", count: 18, location: "North Coast & New Cairo", logoImg: "images/developers_images/intertia.png" },
    { name: "City Edge", count: 26, location: "New Alamein & Sheikh Zayed", logoImg: "images/developers_images/cityedge.jpg" },
    { name: "Karmell", count: 15, location: "El Sheikh Zayed", logoImg: "images/developers_images/almarasem.jpg" }
  ]
};

// Helper formatters
function formatCurrencyEGP(amount) {
  if (amount === undefined || amount === null) return "0 EGP";
  return amount.toLocaleString("en-US") + " EGP";
}
